[package]
name = "rpi-ds18b20-rust"
version = "0.1.0"
authors = ["Alex Wendland <me@alexwendland.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
